name: CMake

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  gtest:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        cxx: [g++]
        stdcxx: [14, 17]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: test
      run: |
        cd tests
        cmake -S . -B build
        cmake --build build
        cd build && ctest
      env:
        CXX: ${{ matrix.cxx }}
        STDCXX: ${{ matrix.stdcxx }}
        GTEST_COLOR: "1"
