name: Unit tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  gtest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: test
      run: |
        cd tests
        cmake -S . -B build
        cmake --build build
        cd build && ctest
      env:
        GTEST_COLOR: "1"
