name: CMake

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: test
      run: |
        cd tests
        cmake -S . -B build
        cmake --build build
        cd build && ctest
